### ISSUE TITLE
Playlist.write fails

### ISSUE THREAD

**Issue by TypicalFence** [dem214/xspf-lib#2]
**Describe the bug**
Calling Playlist.write makes stuff explode.

I am running python 3.8.5.

**To Reproduce**
1. Run the examples in the Read me
2. Be presented with a stacktrace

```
Traceback (most recent call last):
  File "aaa.py", line 24, in <module>
    playlist.write("some_tracks.xspf")
  File "/home/fence/.local/lib/python3.8/site-packages/xspf_lib/__init__.py", line 372, in write
    self.xml_eltree.write(file_or_filename,
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 770, in write
    qnames, namespaces = _namespaces(self._root, default_namespace)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 880, in _namespaces
    add_qname(tag)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 864, in add_qname
    raise ValueError(
ValueError: cannot use non-qualified names with default_namespace option
```

It appears to write it when you comment out the `default_namespace` argument on line 376. 
I am honestly not too familiar with ElementTree module, its just what I observed, maybe its also related to https://bugs.python.org/issue17088

**Comment by dem214** [comment]
Hello there, thanks for your feedback!
I checked example and this is really don't work even on my PC (but I swear, I double swear this worked earlier :) )
I made some fixing and published it in new version 0.1.3, so you can check this again.
Thank you!
